version: '3'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    networks:
      - default
      - nginx-proxy
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
